#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu

* Theoretical Astrophysics - Stellar Evolution

[[https://lavinia.as.arizona.edu/~mrenzo/courses/545/index.html][https://img.shields.io/website-up-down-green-red/http/shields.io.svg]]

Material developed for the =ASTR/PTYS 545= course (one semester) at the
Department of Astronomy and Steward Observatory of the University of
Arizona (Spring semester 2026).

 - [[./org-content/syllabus.org][Syllabus]]
 - [[./org-content/lectures.org][Lectures]]
 - [[./org-content/projects.org][Projects and presentations]]

* Technical details

The lecture notes are written as emacs =org= files available in
[[./org-content]] and exported to =html= (available [[https://lavinia.as.arizona.edu/~mrenzo/courses/545/index.html][online here]], the output
of the export also relies on the =css= and =html= templates in
[[./html-content]]), and in =pdf= (compiled with =LaTeX=) for printing and
annotating before I give a lecture.

** How to build it?

The script =build.sh= is the main script to build the website. It first
checks if the flag =--all= was passed as an argument, in which case it
will build all the =org= files, otherwise it will look for the =org=-files
that have been modified using =git diff= and only build those.

The script actually calls emacs to do the build (with =-Q= flag so the
process does not depend on my specific emacs configuration), which is
run by =build.sh= in =script= mode to run the =elisp= script =build-site.el=.

=build-site.el= checks for the =htmlize= and =ox-publish= packages, and
installs them locally if they are not available, then exports to =html=
the appropriate files (either all the =org= files or the ones modified
since the last commit) to the folder =html-content=, and hands back the
control to =build.sh=, which finishes things by pushing to this repo and
rsync the =html= files from the server where I host the website (this is
just because the server is very old and I cannot have a modern version
of emacs to build directly there).

* Log

Each semester's website will be archived as a release.

* TODO Feedback
- [ ] clarify instructions for submission of final project materials
  - submission of manuscript: email cc-ing instructor and referees, =author_last_name_topic.pdf=
  - referee reports: email cc-ing author and instructor (but *not* the other referee), =referee_last_name_referee_author_last_name_topic.pdf=
- [ ] provide examples of referee report and written manuscript?
- [ ] HW on Chandrasekhar mass: design approximation bypassing Lane-Emden equation?
- [ ] =MESA-web= final condition for WD models fails
- [ ] mid-term exam question: when is R_{\odot} reached should specify "in gravothermal equilibrium"
- [ ] mid-term exam question: R(Z) better done with radiative envelope, ask comparison at fixed X_{c} and fixed t
- [ ] mid-term exam: too long to go through without TA
