#+Title: ASTR545 - SNIa
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu
#+NEXT_PAGE: notes-lecture-GWprog.org
#+PREVIOUS_PAGE: projects.org

*Materials:* Hansen & Kawaler book Sec. 2.6.3,

* Explosion of WDs

We have discussed in the [[./notes-lecture-SNe.org][core-collapse lecture]] the collapse of an iron
(or in some cases ONeMg) core and how it can trigger th core-collapse
SN explosion of a massive star. Here, we will instead discuss
explosions of low-mass stars ending their life as WDs.

In isolation, a WD can only cool down, possibly crystallize releasing
some latent heat to slow down the cooling, and continue cooling
further afterwards, until it becomes too faint and cold to be
detected. Ultimately this should produce a "black dwarf" (in a time
longer than the age of the Universe).

While in a hypothetical "black dwarf" the density may be so high that
density-driven nuclear reactions (pico-nuclear reactions) could occur
and start a dynamical phase of evolution (e.g., [[https://ui.adsabs.harvard.edu/abs/2020MNRAS.497.4357C/abstract][Caplan 2020]]), the fact
that the Universe is too young to have formed black dwarfs guarantees
that this is /not/ part of the transients we /do/ observe.

A WD that is /not/ in isolation, but instead is part of a binary system,
may be perturbed by the companion (e.g. during a mass-transfer phase),
which can /also/ lead to dynamical and explosive consequences. Here, we
focus on these explosions, and more specifically the ones that will
result in a full destruction of the WD -- so called SNIa.

** A zoo within a zoo: WD explosions landscape



* Phillips relation

* D6 stars
