#+Title: ASTR545 - Tides
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu
#+PREVIOUS_PAGE: notes-lecture-RLOF.org
#+NEXT_PAGE: notes-lecture-SNe.org

*Materials:* Zahn 1977

* Tides

When considering the effect of a gravitational potential across an
/extended/ mass (i.e., whose size is not negligible compared to the size
of the system), we need to consider *tides due to the difference in
gravitational forces across an extended body*.

:Question:
- *Q*: for which kind of binaries do we expect tides to be relevant?
:end:

Consider the simplest case of a binary system with masses $M$ and $m$
at a separation $r$. For simplicity, let's assume $M$ to be a point
mass so we don't have to deal with its structure.

*N.B.:* This may not be a bad approximation when the star $M$ is a
compact object (NS, BH, or WD).

The gravitational force acting between the two bodies is
#+begin_latex
\begin{equation}\label{eq:newtonian_grav}
\mathbf{F}_{\rm grav} = -\frac{GMm}{r^{2}}\mathbf{\hat{r}} \ \ .
\end{equation}
#+end_latex
If the star $m$ has a radius $R_{\star}$, there is a difference in the
gravitational force across the side facing the companion and the one
facing away, hence a tidal field
#+begin_latex
\begin{equation}\label{eq:tide_Def}
\mathbf{T}(\mathbf{r}) = \mathbf{F}_{\rm grav}(\mathbf{r}) - \mathbf{F}_{\rm grav}(\mathbf{r}+R_{\star}\mathbf{\hat{r}}) = -GMm\left(\frac{1}{r^{2}}-\frac{1}{(\mathbf{r}+R_{\star}\mathbf{\hat{r}})^{2}}\right)\mathbf{\hat{r}} \ \ .
\end{equation}
#+end_latex
If the stellar radius is much smaller than the separation ($R_{\star}\ll r$ but
non-negligible), we can Taylor expand the parenthesis to obtain:
#+begin_latex
\begin{equation}
\left(\frac{1}{r^{2}}-\frac{1}{(\mathbf{r}+R_{\star}\mathbf{\hat{r}})^{2}}\right) \simeq \frac{2R_{\star}}{r^{3}} \ \ ,
\end{equation}
#+end_latex
and thus:
#+begin_latex
\begin{equation}
\mathbf{T}(\mathbf{r}) = - \frac{2GMmR_{\star}}{r^{3}}\mathbf{\hat{r}} \propto \frac{1}{r^{3}} \ \ .
\end{equation}
#+end_latex

To first order in $R_{\star}/r$, the tidal forces resulting from differences
in the gravitational field created by a body scale like $\propto r^{-3}$,
meaning the tidal field drops /faster/ than the gravitational field $\propto
r^{-2}$. For wide systems tides are usually negligible (although this
depends also on the masses and radii). Viceversa, for very close
binaries, tides can be an important perturbation.

** Non-perturbative tides: tidal disruption radius
From the functional dependence on $r$, we can see that at small
separation the tidal field can become strong. Could it exceed the
self-gravity of the star $m$?
#+begin_latex
\begin{equation}\label{eq:tidal_dis_radius}
\lvert \mathbf{T} \rvert \ge \frac{Gm^{2}}{R_{\star}^{2}} \Rightarrow r\le r_{\rm TD} = \left(\frac{M}{m}\right)^{1/3} R_{\star} \ \ ,
\end{equation}
#+end_latex
If the separation $r$ is smaller than the so-called tidal-disruption
radius $r_{\rm TD}$, the tidal field generated by $M$ will tear apart the
star $m$, that is we get a *tidal disruption event*.

This usually happens with $M\simeq M_{\rm SMBH} \gtrsim 10^{6}M_{\odot}$, i.e., for
stars forming a binary (typically on an hyperbolic orbit) with a
super-massive BH. However, the resulting transient can be detected in
electromagnetic observations only if the tidal disruption occurs
outside of the event of horizon, that is $r_{\rm TD} \ge r_{g} = 2GM/c^{2}$,
which effectively puts a $(m, R_{\star{}})$-dependent upper limit on $M$ for a
tidal disruption event to occur.

:Question:
- *Q*: For an intermediate mass BH of $M=1000\,M_{\odot}$, what type of star
  could lead to a tidal disruption event (in terms of $m$ and $R_{\star}$)?
:end:

** Tides as a perturbation
Let's now consider the regime $r\gg r_{\rm TD}$, in which case (cf. Eq.
\ref{tidal_dis_radius}), the tidal field $\mathbf{T}$ is a small
perturbation over the self-gravity of the stars.

The presence of this perturbation will cause deviations from spherical
symmetry (since the perturbation is /not/ a central force!). This means
the gas of star $m$ will have a bulge (more extended than a sphere
along the separation).

Let's now consider the interplay between tides and stellar rotation.
If the star is rotating non-synchronously with the orbit (i.e.,
$\omega_{\rm surf}\ne\omega_{\rm orb}$), then the bulge will lag (if $\omega_{\rm surf}<\omega_{\rm
orb}$) or anticipate the orbit (if $\omega_{\rm surf}\ge\omega_{\rm orb}$, which is a
situation observed in nature, cf. [[https://ui.adsabs.harvard.edu/abs/2024A%26A...684A..35B/abstract][Britavskiy et al. 2024]], [[https://ui.adsabs.harvard.edu/abs/2024A%26A...684A..35B/abstract][Naze et al.
2026]]).

:Question:
- *Q*: Does the deformed non-synchronously rotating star structure match
  equipotential surfaces?
:end:

The deformation induced by tides, combined with the lag/anticipation
make the structure of star $m$ /not/ match equipotential surfaces: we
have an "out-of-equilibrium" situation!

In the limit where the perturbations induced by tides are /small/, these
will excite waves in the star, and the key question for tidal
evolution is /how are these waves excited by tides dissipated/? The
dissipation rate determines the (poorly known) rate at which the
system will recover equilibrium.

We have already implicitly defined the equilibrium condition! If
$\omega_{\rm surf}=\omega_{\rm orb}$ there is no lag/anticipation, and star $m$
fills equipotentials of the combined potential of the two bodies $M$
and $m$. However, this works only if there is no change in orbital
velocity across the orbit, so only for circular binaries! In the case
of an eccentric binary, the bulge may not be able to follow the change
in equipotential surfaces along the orbital period. Therefore, the
equilibrium condition (which minimizes the orbital energy of the
system) is both:
1. circularization of the orbit ($e=0$)
2. synchronization of rotation and orbital revolution (\omega_{\rm surf}=\omega_{\rm orb})

If an binary fullfils condition 2. with $e\ne0$, we talk about
*pseudo-synchronization*, while both 1. and 2. correspond to a fully
synchronized orbit.

*** Tidal evolution for a generic orbit
